# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portHome', '0002_auto_20170327_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portHome.Project'),
        ),
    ]
