# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portHome', '0003_auto_20170327_0540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='AdditionalImage',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(default='http://strmstr.com/images/coming-soon.png', max_length=200),
            preserve_default=False,
        ),
    ]
