# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portHome', '0005_auto_20170327_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Technology',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='languages',
            new_name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.CharField(default='python', max_length=200),
            preserve_default=False,
        ),
    ]
